/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shuwill_openssl_natives_jni_X509JniNative */

#ifndef _Included_com_shuwill_openssl_natives_jni_X509JniNative
#define _Included_com_shuwill_openssl_natives_jni_X509JniNative
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509New
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509Free
  (JNIEnv *, jclass, jlong);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509NameNew
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509NameFree
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509NameAddEntryByTxt
  (JNIEnv *, jclass, jlong, jstring, jint, jobject, jint, jint, jint);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509SetVersion
  (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509SetNotBefore
  (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509SetNotAfter
  (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509SetSerialNumber
  (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509SetSubjectName
  (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509SetIssuerName
  (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509SetPubkey
  (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509AddExt
  (JNIEnv *, jclass, jlong, jlong, jint);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509ExtensionNew
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509ExtensionFree
  (JNIEnv *, jclass, jlong);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509V3ExtNconfNid
  (JNIEnv *, jclass, jint, jstring, jlong issuer, jlong, jlong, jlong, jint);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509V3ExtI2d
  (JNIEnv *, jclass, jint, jint, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509Sign
  (JNIEnv *, jclass, jlong, jlong, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_i2dX509Bio
  (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_d2iX509Bio
        (JNIEnv *, jclass, jlong);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509ReqNew
        (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509ReqFree
        (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509ReqSetSubjectName
        (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509ReqGetSubjectName
        (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509ReqSetPubkey
        (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509ReqSign
        (JNIEnv *, jclass, jlong, jlong, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_i2dX509ReqBio
        (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_d2iX509ReqBio
        (JNIEnv *, jclass, jlong);

JNIEXPORT jstring JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509NameOneline
        (JNIEnv *, jclass, jlong);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509GetVersion
        (JNIEnv *, jclass, jlong);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509GetSubjectName
        (JNIEnv *, jclass, jlong);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509GetIssuerName
        (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509Print
        (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509GetX509Pubkey
        (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_X509JniNative_X509PubkeySetParam
        (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
