/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shuwill_openssl_natives_jni_EvpJniNative */

#ifndef _Included_com_shuwill_openssl_natives_jni_EvpJniNative
#define _Included_com_shuwill_openssl_natives_jni_EvpJniNative
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpMdCtxNew
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpMdCtxReset
  (JNIEnv *, jclass, jlong);

JNIEXPORT void JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpMdCtxFree
  (JNIEnv *, jclass, jlong);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpGetDigestByName
  (JNIEnv *, jclass, jstring);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpGetDigestByNid
  (JNIEnv *, jclass, jint);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpGetDigestByObj
  (JNIEnv *, jclass, jlong);

JNIEXPORT void JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpMdFree
  (JNIEnv *, jclass, jlong);

JNIEXPORT jstring JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpMdGetName
  (JNIEnv *, jclass, jlong);

JNIEXPORT jstring JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpMdGetDescription
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpMdGetSize
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpMdCtxGetSize
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpDigestInit
  (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpDigestUpdate
  (JNIEnv *, jclass, jlong, jobject, jint);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpDigestFinal
  (JNIEnv *, jclass, jlong, jobject, jobject);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpCipherCtxNew
  (JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpCipherCtxReset
  (JNIEnv *, jclass, jlong);

JNIEXPORT void JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpCipherCtxFree
  (JNIEnv *, jclass, jlong);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpGetCipherByName
  (JNIEnv *, jclass, jstring);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpGetCipherByNid
  (JNIEnv *, jclass, jint);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpGetCipherByObj
  (JNIEnv *, jclass, jlong);

JNIEXPORT void JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpCipherFree
  (JNIEnv *, jclass, jlong);

JNIEXPORT jstring JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpCipherGetName
  (JNIEnv *, jclass, jlong);

JNIEXPORT jstring JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpCipherGetDescription
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpCipherGetBlocksize
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpCipherGetMode
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpCipherIs
  (JNIEnv *, jclass, jlong, jstring);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpCipherGetKeyLength
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpCipherCtxGetKeyLength
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpCipherCtxSetKeyLength
  (JNIEnv *, jclass, jlong, jint);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpCipherCtxSetPadding
  (JNIEnv *, jclass, jlong, jint);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpCipherGetIvLength
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpCipherCtxGetIvLength
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpBytesToKey
  (JNIEnv *, jclass, jlong, jlong, jobject, jobject, jint, jint, jobject, jobject);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpCipherInit
  (JNIEnv *, jclass, jlong, jlong, jobject, jobject, jint);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpCipherUpdate
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject, jint);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpCipherFinal
  (JNIEnv *, jclass, jlong, jobject, jobject);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpPkeyCtxNewId
  (JNIEnv *, jclass, jint, jlong);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpPkeyCtxNew
  (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT void JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpPkeyCtxFree
  (JNIEnv *, jclass, jlong);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpPkeyNew
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpPkeyFree
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpPkeyCtxIs
  (JNIEnv *, jclass, jlong, jstring);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpPkeyKeygenInit
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpPkeyParamgenInit
  (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpPkeyGenerate
  (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpPkeyParamgen
  (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpPkeyKeygen
  (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpPkeyCtxSetRsaKeygenBits
  (JNIEnv *, jclass, jlong, jint);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpPkeyCtxSetEcParamgenCurveNid
  (JNIEnv *, jclass, jlong, jint);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpPkeyCtxSetEcParamenc
  (JNIEnv *, jclass, jlong, jint);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpPkey2Pkcs8
        (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_i2dPkcs8PrivkeyInfoBio
        (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_d2iPkcs8PrivkeyInfoBio
        (JNIEnv *, jclass, jlong);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpPkcs82Pkey
        (JNIEnv *, jclass, jlong);

JNIEXPORT void JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_pkcs8PrivkeyInfoFree
        (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_i2dPubkeyBio
  (JNIEnv *, jclass, jlong, jlong);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_d2iPubkeyBio
        (JNIEnv *, jclass, jlong);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_X509ReqGetPubkey
        (JNIEnv *, jclass, jlong);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_X509GetPubkey
        (JNIEnv *, jclass, jlong);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_PEMWriteBioPKCS8PrivateKey
        (JNIEnv *, jclass, jlong, jlong, jlong, jobject);

JNIEXPORT jlong JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_i2dPKCS8PrivateKeyNidBio
        (JNIEnv *, jclass, jlong, jlong, jint, jobject);

JNIEXPORT jint JNICALL Java_com_shuwill_openssl_natives_jni_EvpJniNative_evpPkeySetType
        (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
